# .streamlit/config.toml
[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501 # Default Streamlit port, usually fine

[browser]
gatherUsageStats = false # <--- THIS IS THE KEY LINE FOR THE PERMISSION ERROR
